# Generated by Django 4.1.3 on 2022-12-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200317_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kerkesat',
            new_name='TutorRequest',
        ),
    ]
