# Generated by Django 4.1.3 on 2022-12-09 15:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0015_program_delete_klasa_rename_lendet_courses_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='klasa',
        ),
        migrations.RenameModel(
            old_name='Courses',
            new_name='Lendet',
        ),
    ]
