# Generated by Django 4.1.3 on 2022-12-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_rename_pershkrimi_klasa_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lendet',
            old_name='imazhi_lendes',
            new_name='course_image',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='krijuar_me',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='krijues',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='pershkrimi',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='klasa',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='titulli',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lenda',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='pozicioni',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='titulli',
            new_name='title',
        ),
    ]
