# Generated by Django 4.1.4 on 2022-12-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_rename_imazhi_lendes_lendet_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendet',
            name='course_books_link',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
